services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 20s
      timeout: 5s
      retries: 5

  hotel-service:
    build:
      context: .
      dockerfile: hotel-service/Dockerfile
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    depends_on:
      eureka-server:
        condition: service_healthy
      hotel-service:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      eureka-server:
        condition: service_healthy
      booking-service:
        condition: service_started
      hotel-service:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

