spring:
  datasource:
    url: jdbc:h2:mem:bookingdb-test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    root: WARN

app:
  security:
    jwt:
      secret: c2VjcmV0LWZvci1ib29raW5nLXRlc3Q=
      validity-seconds: 3600
  resilience:
    failure-rate-threshold: 10
    sliding-window-size: 2
    minimum-number-of-calls: 2
    permitted-calls-in-half-open-state: 1
    wait-duration-in-open-state-ms: 1000
    timeout-ms: 1000
