spring:
  datasource:
    url: jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: INFO

app:
  security:
    jwt:
      secret: dGhpc0lzQWRvY2tlclNlY3JldEJvb2tpbmc=
      validity-seconds: 3600
