spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.booking: DEBUG

app:
  security:
    jwt:
      secret: c2VjcmV0LWZvci1ob3RlbC1zZXJ2aWNl
      validity-seconds: 3600

