spring:
  application:
    name: eureka-server
  cloud:
    compatibility-verifier:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    compatibility-verifier:
      enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: false
    fetch-registry: false

